version: '3.2'
services:
  springapp:
    image: vijju14nov/spring-boot-mongo:latest
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    networks:
    - bridge_test
    depends_on:
    - mongo
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
    - vol_demo:/data/db
    networks:
    - bridge_test
volumes:
  vol_demo:
networks:
  bridge_test:
